<aside class ="swiper mySwiper">
  <!-- Additional required wrapper -->
  <div class="swiper-wrapper">
    <!-- Slides -->
    <div class="swiper-slide "><img src="/app/public/images/wireframes/saladepates.webp" alt="salade du jour " class="imag "
"></div>
    <div class="swiper-slide" ><img src="/app/public/images/wireframes/smoothiefraise.webp" alt="salade du jour " class="imag "
"></div>
    <div class="swiper-slide "><img src="/app/public/images/wireframes/choco.webp" alt="salade du jour " class="imag "
"></div>
    
  </div>
  <!-- If we need pagination -->
  <div class="swiper-pagination"></div>

  <!-- If we need navigation buttons -->
  <div class="swiper-button-prev "></div>
  <div class="swiper-button-next "></div>

  <!-- If we need scrollbar -->
  <div class="swiper-scrollbar"></div>
  
</aside>

<section class="card ml-2 mr-2">
  <div class="container mx-auto px-4 text-center">
    <h2 class="text-3xl font-semibold text-[--color-titres] mb-6">Menu du Jour</h2>
    <p class=" mb-8">Découvrez nos spécialités fraîches du jour</p>

    <article class="card bg-bgcardart">
      <!-- Plat -->
      <div class="mb-6 md:mb-0">
        <h3 class="text-2xl font-medium text-[--color-rose] mb-2">Salade de Pates</h3>
        <img src="/app/public/images/wireframes/saladepates.webp" alt="salade du jour " class="imag w-full h-full object-contain" />
        <p class="text-titres">Salade d'avocat et tomates cerises</p>
        <p class="text-sm text-gray-500">Avec une vinaigrette au basilic frais</p>
      </div>

      <!-- Boisson -->
      <div class="mb-6 md:mb-0">
        <h3 class="text-2xl font-medium text-[--color-rose] mb-2">Boisson</h3>
        <img src="/app/public/images/wireframes/smoothiefraise.webp" alt="salade du jour " class="imag w-full h-full object-contain" />
        <p class="text-[--color-titres]">Jus de citron maison</p>
        <p class="text-sm text-gray-500">Pressé du jour, servi frais</p>
      </div>

      <!-- Dessert -->
      <div>
        <h3 class="text-2xl font-medium text-[--color-rose] mb-2">Dessert</h3>
        <img src="/app/public/images/wireframes/choco.webp" alt="salade du jour " class="imag w-full h-full object-contain" />
        <p class="text-[--color-titres]">Mousse au chocolat</p>
        <p class="text-sm text-gray-500">Légère et onctueuse</p>
      </div>
    </article>
  </div>
</section>

<section>

</section>

