<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aura-Fine</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
/>

    <link href="app/public/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="app/public/css/theme.css" />
</head>
<body class= "bg-beige" >

<header
  >
  <h1>AuraFine</h1>
  <p class="text-center p-1 m-2">Le rafinnement qui vous ressemble </p>
  <!-- <image class="src="/app/public/images/wireframes/logo-mode-sombre.webp"></image> -->
</header>

    <main>
        <?php include $template ?>
    </main>

    <footer class="bg-amber-50 text-titres py-6">
        <section class="container mx-auto px-4 text-center">
            <article class= "">
                <h3 class="mb-2">Contacts</h3>
                <p class="text-sm font-semibold">AuraFine</p>
                <p class="text-sm">Le raffinement qui vous ressemble</p>
                <p class="text-sm">Dakar, Sénégal</p>
                <p class="text-sm">Email: info@aurafine.com</p>
                <p class="text-sm">Tel: +221-77-473-13-87</p>

            </article>

            <article class="mt-6">
                <h3 class="text-lg font-semibold mb-2">Liens Utiles</h3>
                <ul class="text-sm">
                <li><a href="#" class="hover:text-gray-400">Menu</a></li>
                <li><a href="#" class="hover:text-gray-400">À Propos</a></li>
                <li><a href="#" class="hover:text-gray-400">Articles et conseils</a></li>
                </ul>
            </article>

            <article class="mt-6">
                <p class="text-rose text-sm">&copy; 2025 AuraFine. Tous droits réservés.</p>
                <div class="flex space-x-4 mt-2 md:mt-0 justify-center">
                    <a href="#" class="hover:text-gray-400"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="hover:text-gray-400"><i class="fab fa-tiktok"></i></a>
                    <a href="#" class="hover:text-gray-400"><i class="fab fa-instagram"></i></a>
                </div>
            </article>
        
        </section>
    </footer>
<!-- swiper -->
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" defer></script>
    <script src="/app/public/js/slider.js" defer></script>
</body>
</html>